# Generated by Django 4.1.6 on 2023-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp', models.IntegerField(help_text='SMARTER Work Package number (ex. 4')),
                ('task', models.CharField(help_text='SMARTER taks (ex 2.1)', max_length=50)),
                ('species', models.SmallIntegerField(choices=[(0, 'Sheep'), (1, 'Goat')], help_text='Species (Goat or Sheep)')),
                ('data_type', models.CharField(help_text='Data description', max_length=255)),
                ('owner', models.CharField(help_text='Who owns data (ex. INRA)', max_length=50)),
                ('embargo', models.BooleanField(null=True)),
                ('time_series', models.BooleanField(null=True)),
                ('individual_data', models.BooleanField(null=True)),
                ('contact', models.CharField(max_length=50)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
